// SPDX-License-Identifier: MIT
// Small freestanding x86-64 micro-benchmark set for comparing FEX builds / configurations (TSO, SMC mode, LTO ...).
// Prints one "name  milliseconds" line per test. Build with ../ptrace-inject/build.sh-style flags (see build.sh here).
#ifndef INVAL_MODE
#define INVAL_MODE 0
#endif
#ifndef INVAL_THREADS
#define INVAL_THREADS 0
#endif
typedef unsigned long u64; typedef long i64; typedef unsigned int u32; typedef unsigned char u8;
#include <immintrin.h>

static inline i64 sc(i64 n, i64 a, i64 b, i64 c) { i64 r; __asm__ volatile("syscall" : "=a"(r) : "a"(n), "D"(a), "S"(b), "d"(c) : "rcx", "r11", "memory"); return r; }
static inline i64 sc4(i64 n, i64 a, i64 b, i64 c, i64 d) { i64 r; register i64 r10 __asm__("r10") = d; __asm__ volatile("syscall" : "=a"(r) : "a"(n), "D"(a), "S"(b), "d"(c), "r"(r10) : "rcx", "r11", "memory"); return r; }
static u64 now_ns(void) { struct { i64 s, n; } t; sc(228, 1, (i64)&t, 0); return (u64)t.s * 1000000000ull + (u64)t.n; }
static void out(const char* s) { u64 n = 0; while (s[n]) ++n; sc(1, 1, (i64)s, (i64)n); }
static void num(u64 v) { char b[24]; int i = 23; b[i] = 0; if (!v) b[--i] = '0'; while (v) { b[--i] = '0' + v % 10; v /= 10; } out(b + i); }
static void report(const char* name, u64 t0) { out(name); out("  "); num((now_ns() - t0) / 1000000); out(" ms\n"); }

extern u64 (*tf_table[4096])(u64);
static volatile u64 sink;
static u64 xs = 88172645463325252ull;
static inline u64 rnd(void) { xs ^= xs << 13; xs ^= xs >> 7; xs ^= xs << 17; return xs; }

enum { MB = 1 << 20 };
static u8 bufa[64 * MB], bufb[64 * MB];
static u32 chase[4 * MB];                       // 16 MB pointer-chasing ring

__attribute__((noinline)) static void t_alu(void) {
  u64 t = now_ns(), a = 1, b = 2;
  for (u64 i = 0; i < 300000000ull; ++i) { a = a * 6364136223846793005ull + b; b ^= a >> 17; b += i; }
  sink = a ^ b; report("alu_300M", t);
}
__attribute__((noinline)) static void t_stream(void) {
  u64 t = now_ns();
  for (int r = 0; r < 12; ++r) { for (u64 i = 0; i < sizeof bufa; i += 8) *(u64*)(bufb + i) = *(u64*)(bufa + i) + i; }
  sink = bufb[77]; report("stream_copy_768MB", t);
}
__attribute__((noinline)) static void t_chase(void) {
  for (u32 i = 0; i < 4 * MB; ++i) chase[i] = i;
  for (u32 i = 4 * MB - 1; i > 0; --i) { u32 j = (u32)(rnd() % (i + 1)); u32 x = chase[i]; chase[i] = chase[j]; chase[j] = x; }
  u64 t = now_ns(); u32 p = 0;
  for (u64 i = 0; i < 40000000ull; ++i) p = chase[p];
  sink = p; report("pointer_chase_40M", t);
}
__attribute__((noinline)) static void t_branchy(void) {
  u64 t = now_ns(), acc = 0;
  for (u64 i = 0; i < 120000000ull; ++i) { u64 r = rnd(); if (r & 1) acc += r; else if (r & 2) acc ^= r; else if (r & 4) acc -= r >> 3; else acc += i; }
  sink = acc; report("branchy_120M", t);
}
__attribute__((noinline)) static void t_sse(void) {
  __m128 a = _mm_set1_ps(1.0f), b = _mm_set1_ps(1.0000001f), c = _mm_set1_ps(0.5f);
  u64 t = now_ns();
  for (u64 i = 0; i < 150000000ull; ++i) { a = _mm_add_ps(_mm_mul_ps(a, b), c); c = _mm_sub_ps(c, _mm_set1_ps(1e-9f)); }
  float f[4]; _mm_storeu_ps(f, a); sink = (u64)f[0]; report("sse_150M", t);
}
__attribute__((noinline)) static void t_syscall(void) {
  u64 t = now_ns(); for (int i = 0; i < 1000000; ++i) sc(39, 0, 0, 0); report("getpid_1M", t);
}
__attribute__((noinline)) static void t_atomics(void) {
  static volatile u64 v; u64 t = now_ns();
  for (u64 i = 0; i < 50000000ull; ++i) { __atomic_fetch_add(&v, 1, __ATOMIC_SEQ_CST); __atomic_store_n(&v, i, __ATOMIC_RELEASE); sink = __atomic_load_n(&v, __ATOMIC_ACQUIRE); }
  report("atomics_50M", t);
}
__attribute__((noinline)) static void t_indirect(void) {
  u64 t = now_ns(), acc = 1;
  for (u64 i = 0; i < 100000000ull; ++i) acc = tf_table[rnd() & 4095](acc);
  sink = acc; report("indirect_calls_100M", t);
}
// Translation throughput: executes a large straight-line function exactly once (JIT-bound, not execution-bound).
extern void bigcode(void);
#include "bigcode.h"   // generated by gen_bigcode.py
__attribute__((noinline)) static void t_jit(void) { u64 t = now_ns(); bigcode(); report("jit_cold_bigcode", t); }


// --- code-range invalidation cost: mprotect/munmap churn on DATA pages while many other threads exist -------------------
static u8 mpage[4096] __attribute__((aligned(4096)));
static volatile int park_word;
static u8 tstack[512][16384] __attribute__((aligned(16)));
static void thread_main(void) {
  volatile u64 x = 1; for (int i = 0; i < 1000; ++i) x = x * 3 + i;       // run a little code so the thread has translated blocks
  for (;;) sc4(202, (i64)&park_word, 128 /* FUTEX_WAIT_PRIVATE */, 0, 0);  // futex(&park_word, WAIT, 0, NULL)
}
static long spawn(void (*fn)(void), void* top) {
  long ret; register long r10 __asm__("r10") = 0; register long r8 __asm__("r8") = 0; register void (*r9)(void) __asm__("r9") = fn;
  const long flags = 0x100 | 0x200 | 0x400 | 0x800 | 0x10000 | 0x40000;    // VM|FS|FILES|SIGHAND|THREAD|SYSVSEM
  __asm__ volatile("syscall\n test %%rax, %%rax\n jnz 1f\n call *%%r9\n mov $60, %%eax\n xor %%edi, %%edi\n syscall\n 1:"
                   : "=a"(ret) : "a"(56L), "D"(flags), "S"(top), "d"(0L), "r"(r10), "r"(r8), "r"(r9) : "rcx", "r11", "memory");
  return ret;
}
__attribute__((noinline)) static void t_invalidate(int nthreads, const char* name) {
  for (int i = 0; i < nthreads; ++i) spawn(thread_main, tstack[i] + 16384);
  for (volatile int w = 0; w < 2000000; ++w) {}                              // let the threads start
  u64 t = now_ns();
  for (int i = 0; i < 50000; ++i) { sc(10, (i64)mpage, 4096, 1); sc(10, (i64)mpage, 4096, 3); }
  out(name); out("  "); num((now_ns() - t) / 1000); out(" us  (100k mprotect calls)\n");
}

__attribute__((used)) static void entry_c(void) {
  out("fexbench\n"); if (INVAL_MODE) { t_invalidate(INVAL_THREADS, "mprotect_churn"); sc(231,0,0,0); } t_jit(); t_alu(); t_stream(); t_chase(); t_branchy(); t_sse(); t_syscall(); t_atomics(); t_indirect();
  sc(231, 0, 0, 0);
}
__attribute__((naked, used)) void _start(void) { __asm__ volatile("and $-16, %rsp\n call entry_c\n"); }
